name: The Wall
author: plasm
category: Interface
description: "The Wall is a plugin designed to create walls of infinite dimensions. Its flexibility allows different applications, from infinite wall mode to Coda slider mode. The Wall creates compatible interfaces with the newer browsers and iPhone and iPad mobile devices."
tags: [contents, coda, carousel, mobile]
docs: http://wall.plasm.it/documentation/
demo: http://wall.plasm.it/examples/
current: 1.0
copyright: "&copy; [Marco Dell'Anna](http://www.plasm.it)"

sources:
  - "Source/wall.js"
